version: 2.1

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo test

jobs:
  daily-message:
    machine: true
    parameters:
      message:
        type: string
    steps:
      - print:
          message: Printing test

workflows:
  my-workflow:
    jobs:
      - daily-message:
         message: echo test
