version: 2
jobs:
  test:
    working_directory: ~/crm-dashboard
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: crm-dashboard-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: crm-dashboard-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: xvfb-run -a npm run e2e --configuration=protractor-ci.conf.js
  build:
    steps:
      - checkout
      - run:
        name: Set Docker Tag
        command: |
          export TAG=if [$CIRCLE_BRANCH=="master"] then "latest" else $CIRCLE_BRANCH fi
          echo $TAG
      - setup_remote_docker
      - run:
        name: Build Docker Image
        command: docker build . -t crm-dashboard:$TAG -f ./docker/Dockerfile --build-arg CONFIGURATION=$CIRCLE_BRANCH
  publish:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push crm-dashboard:latest

workflows:
  version: 2
  build_and_publish:
    jobs:
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master